### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by martywallace** [ensembleau/vue-squarepay#2]
* Use the template I gave you for moving the component into its own package.
* Populate the `package.json` with everything you can see in [documentation](https://docs.npmjs.com/files/package.json) that you think can be leveraged (e.g. author, description, etc).
* Create a relevant README file.
* Add a LICENSE - use MIT. Most of my projects include this for reference.
* Create a `.gitignore` including things like `.DS_Store` etc.
* Once happy with the package, commit and push to this repository.
* Follow the [`npm publish`](https://docs.npmjs.com/cli/publish) documentation to push the project to our NPM account. The details are in the online accounts spreadsheet. 
    * Make sure the version in the `package.json` is set to something appropriate - probably `0.1.0`. The value here is what version the package will be available as using `npm install`.
    * It's important to also create a tag / release in GitHub that matches this version so it's easy to see the state of the project for that version (NPM does not have a 1-1 version relationship with GitHub).
* Create a blank aurora project, `npm install` the module and give it a whirl.

Once that all works, let's author a series of issues here that we think will bring it to a standard for a `1.0.0` release.

**Comment by dieser** [comment]
Up on [npm ](https://www.npmjs.com/package/vue-squarepay)
